project:
  type: website

website:
  title: "Duncan Howes"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - blog.qmd
      - about.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



